update.php
I think that the solution described in owncloud/core#12932 by adding `openssl.cafile` to `php.ini` only masks the real problem.
Agreed, it will fix the openssl error. But for some reason the redirect still doesn't work as expected. In any case, there's no harm in changing the URL to the correct scheme. Another pro: one less redirect.
=> fix updater URL to https

css/updater.css, templates/admin.php
Set a max width for backups table and note container.
Set the cursor to pointer for the clickable backups entries.
Change the order of the table columns.
=> Make visual changes according to #75.

appinfo/info.xml
Backport of the version number fix https://github.com/owncloud/updater/pull/154
@VicDeo
=> [stable 8.1] Remove bogus redundant version number

css/updater.css, templates/admin.php
A fix for : https://github.com/owncloud/updater/issues/170
I have altered the spacing for the note block-quote, though I have retained the grey background. I think it should stay. All other semantic fixes lie in this PR.
cc @karlitschek @jancborchardt @owncloud/designers
=> Better looking updater in admin section.

templates/admin.php
Follow-up of https://github.com/owncloud/updater/pull/174
There was an error where an `<em>` tag was not closed, which caused all the text below the updater app in the settings to be grey. Since I needed to touch the strings to fix this anyway, I decided to also polish the text further by simplifying it more.
Please review @owncloud/designers @VicDeo @te-online @karlitschek
=> fix unclosed em tag, fix wording

composer.json, composer.lock, pub/js/login.js, pub/js/main.js, src/Controller/IndexController.php, src/Http/Request.php, src/Resources/views/base.php, src/Resources/views/partials/inner.php, src/Resources/views/partials/login.php, src/Utils/ConfigReader.php, vendor/composer/autoload_files.php, vendor/composer/autoload_psr4.php, vendor/composer/installed.json, vendor/symfony/polyfill-php56/LICENSE, vendor/symfony/polyfill-php56/Php56.php, vendor/symfony/polyfill-php56/README.md, vendor/symfony/polyfill-php56/bootstrap.php, vendor/symfony/polyfill-php56/composer.json, vendor/symfony/polyfill-util/Binary.php, vendor/symfony/polyfill-util/BinaryNoFuncOverload.php, vendor/symfony/polyfill-util/BinaryOnFuncOverload.php, vendor/symfony/polyfill-util/LICENSE, vendor/symfony/polyfill-util/README.md, vendor/symfony/polyfill-util/TestListener.php, vendor/symfony/polyfill-util/composer.json
This adds some authentication to the updater using a shared secret in `config.php`. The whole process is cookieless and thus if somebody closes the tab all authentication is gone (which is desired from a security PoV)
To test this define an `updater.secret` in `config.php` and try to access it with a valid or invalid token.
The next step is to add the automagic login from core once this is in. We can do that using the new updatenotification app at https://github.com/owncloud/core/pull/22238.
@VicDeo Please review.
=> Add authentication to updater

src/Tests/Utils/CheckpointTest.php, src/Utils/Checkpoint.php, src/Utils/FilesystemHelper.php
Depending on the PHP config this looks otherwise like that and is broken:
=> Only do a scandir if the folder exists

src/Controller/IndexController.php
* fixes #253
cc @LukasReschke @karlitschek @VicDeo 
Looks like this:
=> Proper error message when /updater is browsed directly.

pub/js/login.js, pub/js/main.js, src/Controller/IndexController.php
PHP used in CGI mode will eat the Authorization header and thus the authentication never worked.
Fixes https://github.com/owncloud/updater/issues/263
Requires https://github.com/owncloud/core/pull/22889
@karlitschek I recommend that we merge this for 9.0.0. Otherwise the updater app will not work for people that use PHP in CGI mode.
=> [stable9] Use custom header

pub/js/login.js, pub/js/main.js, src/Controller/IndexController.php
PHP used in CGI mode will eat the Authorization header and thus the authentication never worked.
Fixes https://github.com/owncloud/updater/issues/263
Requires https://github.com/owncloud/core/pull/22888
=> Use custom header

app/bootstrap.php, application.php
Fixes misuses like in 
```
www-data@tools01:~/owncloud$ php updater/application.php upgrade:checkpoint -h
PHP Warning: include(/var/www/version.php): failed to open stream: No such file or directory in /var/www/owncloud/updater/src/Utils/Locator.php on line 182
PHP Warning: include(): Failed opening '/var/www/version.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/owncloud/updater/src/Utils/Locator.php on line 182
PHP Notice: Undefined variable: OC_Version in /var/www/owncloud/updater/src/Utils/Locator.php on line 185
PHP Warning: implode(): Invalid arguments passed in /var/www/owncloud/updater/src/Console/Application.php on line 148
```
=> Chdir to updater directory before taking any other action

src/Controller/IndexController.php
Thix fixes the message ui shown when wrong password was entered.
Maybe this had been forgotten in #265, #266.
ref issue #263
=> fixes wrong invalid password ui

app/config/container.php, src/Console/Application.php
Fixes #317 
Init logger when datadir is available. Fallback to stderr.
All errors happened when no  logger exists goes to stdout.
=> Write update.log to datadir

app/config/container.php, src/Console/Application.php
All errors happened when no  logger exists goes to stdout.
Backport of #320
=> [Stable9] Init logger when datadir is available. Fallback to stderr.

src/Command/ExecuteCoreUpgradeScriptsCommand.php, src/Utils/Checkpoint.php, src/Utils/Locator.php
Reproduction steps
1. php updater/application upgrade:checkpoint --create
2. php updater/application upgrade:checkpoint --restore _checkpointId_
3. php occ integrity:check-core
Expected `config.sample.php` in `config` dir
Actual `config.sample.php` in OC root dir
=> Fix config.sample.php in oc root dir after restoring a checkpoint

src/Command/CheckSystemCommand.php, src/Command/EnableNotShippedAppsCommand.php, src/Command/ExecuteCoreUpgradeScriptsCommand.php, src/Command/UpgradeShippedAppsCommand.php, src/Utils/AppManager.php, src/Utils/Checkpoint.php, src/Utils/FilesystemHelper.php
Depends on https://github.com/owncloud/updater/pull/346
Fixes https://github.com/owncloud/updater/issues/264
Fixes #336 
Fixes #290
Closes #332
takes care of https://github.com/owncloud/updater/issues/336#issuecomment-216172639
=> Do not create __apps dir.

lib/location/apps.php
Fixes `Signature data not found` https://github.com/owncloud/updater/issues/379#issuecomment-249152842
when migrating to 9.0.5
=> [Stable8.2] check info xml

src/Utils/OccRunner.php
Fixes https://github.com/owncloud/updater/issues/383
To test try to start update from CLI on master/stable9.1/stable9
```
$ php updater/application.php upgrade:start
```
The result is `Symfony\Component\Process\Exception\ProcessFailedException`
=> Use --key=value notation for CLI

src/Command/PostUpgradeCleanupCommand.php
To test:
- Core daily package needs to be patched with https://github.com/owncloud/core/pull/26469
- This patch is applied on top of the installed OC
=> Retrigger integrity check. Fixes #404

.travis.yml, src/Utils/Locator.php
Fixing issue reported at https://github.com/owncloud/administration/pull/111#issuecomment-283978146
extra files are left after update from  9.1.x:
```
Results
=======
- core
- EXTRA_FILE
- updater/nbproject/project.xml
- updater/nbproject/project.properties
```
=> Fix integrity when updating from 9.1.x to master

.travis.yml, src/Utils/Locator.php
Fixing issue reported at
https://github.com/owncloud/administration/pull/111#issuecomment-283940241
extra file `updater/.gitignore` is left after update from any 9.1.x to 9.1.4
=> Fix integrity when migrating from 9.1.0-9.1.3

.travis.yml, src/Utils/Locator.php
Backport of https://github.com/owncloud/updater/pull/416
Reproduction steps:
1. Install 9.0.4
2. Update to 9.0.8 using stable channel 
3. Update to 9.1.4 using daily channel 
4. Do an integrity check:
```
> php occ integr:check-core
- EXTRA_FILE:
- updater/.gitignore:
- expected: 
- current: 7c017a81ca97f082b0d97869336cd41ad0d02e67de4865e33ca031775dc9ea5e9e7f024a4fa8016e58f29e7c4fd90d1633944ffbab37ee4c4ff739443c8d059c
```
to test:
apply the fix on top of 9.0.8 before updating to 9.1.4
=> Fix integrity when migrating from 9.0 to 9.1

app/config/container.php, src/Command/ExecuteCoreUpgradeScriptsCommand.php, src/Command/StartCommand.php
1. use any RC
2. Switch to daily channel
3. Click `Update`
4. Observe Error 500
=> Broken updater fixes

src/Command/ExecuteCoreUpgradeScriptsCommand.php, src/Tests/Command/ExecuteCoreUpgradeScriptsCommandTest.php
1. setup local update server to provide 10.0.1 as an update for 10.0.1
2. execute php updater/application.php upgrade:start
3. observe warning like #425 
Tested manually + covered with unit-test
=> CanBeUpgradedFrom could have multiple versions. Fixes #425

src/Utils/OccRunner.php
Fixes another case of #414  caused by  forwarding an external port to the LAN device behind NAT.
Testing in progress...
=> Skip SSL validation for https://localhost

src/Utils/OccRunner.php
Backport of https://github.com/owncloud/updater/pull/434
>cURL error 51: SSL: no alternative certificate subject name matches target host name 'localhost'
=> [Stable10] Skip SSL validation for https://localhost

src/Utils/OccRunner.php
Backport of https://github.com/owncloud/updater/pull/434
>cURL error 51: SSL: no alternative certificate subject name matches target host name 'localhost'
=> [Stable9.1] Skip SSL validation for https://localhost

src/Utils/OccRunner.php
Backport of https://github.com/owncloud/updater/pull/434
We agreed to backport it to 9.0.x before it reaches EOL as soon as the fix is easy and useful.
This patch was applied by @davitol while testing 9.0.10 to 9.1.6 update in https://github.com/owncloud/administration/pull/139 and is proved to be working
See https://github.com/owncloud/administration/pull/139#issuecomment-331194101
=> [stable9] Skip SSL validation for https://localhost

src/Command/ExecuteCoreUpgradeScriptsCommand.php, src/Utils/AppManager.php
backport of https://github.com/owncloud/updater/pull/469
=> [Stable10] Fix dealing with apps

src/Utils/ConfigReader.php
As reported in several issues, running "php updater/application.php upgrade:detect/info" results in a fatal error. 
Traced issue to an unnecessary/fatal "=" in the command line being provided to "php occ" by ConfigReader.php:109. I am unsure if the issue is with the original change of this code to its current revision (https://github.com/owncloud/updater/commit/f78291eb7651d552bf518b30e195b807746da4b5#diff-ad6d84de30f605974920c65454932957 ) or if the issue is one of a Symfony framework change. 
The root issue appears to be Symfony\Component\Process\Process by way of occRunner->runJson interpreting the array as a key-value pair with an empty argument. This results in the argument to "occ" changing from '--private' to '--private=' ... resulting in a fatal error in "occ" and thus a fatal …
=> Fix for updater/application.php cli fatal errors #472 #482 owncloud/core#31425 

.travis.yml, app/bootstrap.php, composer.json, composer.lock
and explicitly specify the `platform` PHP version in `composer.json` so that it finds an appropriate set of dependencies.
=> Drop PHP 5.6

.travis.yml
Same as PR #541 
Update PHP matrix and fix some travis complaints:
```
root: deprecated key sudo (The key `sudo` has no effect anymore.)
root: missing dist, using the default xenial
root: missing os, using the default linux
root: key matrix is an alias for jobs, using jobs
```
=> Update Travis config to drop PHP 7.0 and add PHP 7.3

composer.lock
```
$ composer update
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 3 updates, 0 removals
- Upgrading symfony/polyfill-ctype (v1.22.1 => v1.23.0)
- Upgrading symfony/polyfill-mbstring (v1.22.1 => v1.23.0)
- Upgrading symfony/polyfill-php80 (v1.22.1 => v1.23.0)
Writing lock file
```
=> Bump symfony/polyfill v1.23.0

Makefile, composer.lock
1) get the PHP  dependencies up-to-date:
```
$ composer update
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 5 updates, 0 removals
- Upgrading phpdocumentor/reflection-docblock (5.2.2 => 5.3.0)
- Upgrading phpdocumentor/type-resolver (1.4.0 => 1.5.1)
- Upgrading phpspec/prophecy (1.13.0 => 1.14.0)
- Upgrading phpunit/phpunit (8.5.20 => 8.5.21)
- Upgrading symfony/debug (v4.4.27 => v4.4.31)
Writing lock file
```
2) Remove 'make' from test-php-unit-dbg
There were fails in CI when running unit tests with coverage. I don't know what happened recently, but is probably related to some changes in the `owncloudci/php` images. 
```
install --prefix build bower
install: unrecognized option '--prefix'
Try 'install --help' for more …
```
=> Bump PHP dependencies and get CI passing

composer.lock
```
$ composer update
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
- Upgrading symfony/deprecation-contracts (v2.5.1 => v2.5.2)
Writing lock file
```
=> Upgrading symfony/deprecation-contracts (v2.5.1 => v2.5.2)

src/Utils/DocLink.php, tests/unit/Utils/DocLinkTest.php, tests/unit/Utils/FetcherTest.php
All doc.owncloud.org replaced with useable doc.owncloud.com links. This also changes some tests. This is probably too much. Let's see...
=> org with com replaced

src/Command/BackupDataCommand.php, src/Command/BackupDbCommand.php, src/Command/CheckSystemCommand.php, src/Command/CheckpointCommand.php, src/Command/CleanCacheCommand.php, src/Command/DetectCommand.php, src/Command/ExecuteCoreUpgradeScriptsCommand.php, src/Command/InfoCommand.php, src/Command/MaintenanceModeCommand.php, src/Command/PostUpgradeCleanupCommand.php, src/Command/PostUpgradeRepairCommand.php, src/Command/PreUpgradeRepairCommand.php, src/Command/RestartWebServerCommand.php, src/Command/StartCommand.php, src/Command/UpdateConfigCommand.php
Symfony 5 will require this, so be prepared.
For Symfony 4 it is optional.
=> Always return an int from Symfony Command execute method

.drone.star
- It is no longer possible to post a GitHub comment when an acceptance test pipeline fails. The token is no longer available to PRs. So remove this from CI.
- The earlyFail setting is not used any more in the code, so remove it.
Part of issue https://github.com/owncloud/QA/issues/820
=> [tests-only] Remove githubComment and unused earlyFail from drone CI

phpstan.neon, src/Command/BackupDataCommand.php, src/Command/BackupDbCommand.php, src/Command/CleanCacheCommand.php, src/Command/PostUpgradeRepairCommand.php, src/Command/PreUpgradeRepairCommand.php, src/Command/RestartWebServerCommand.php, src/Command/UpdateConfigCommand.php
PR #711 made sure to return an `int` command line status from all Symfony command `execute` functions.
But it returned `1` for commands that are not yet implemented. That causes scripts to fail if they call any of the not-yet-implemented commands. That has resulted in upgrades failing when they previously worked (albeit with some steps not implemented). Although some steps were not yet implemented, the actual upgrade was working.
This PR changes the command line status to `0` for not-yet-implemented things. `0` is success for the command line. That puts the behavior back to the way it was.
See discussion in issue #726 
Also, remove phpstan ignoreErrors entries for things that are not errors, Recent versions of phpstan no longer have these false positives, so they are no longer needed in …
=> fix: exit with success command line status 0 for not implemented things

CHANGELOG.md, app/config/container.php, sonar-project.properties
=> chore: Prepare release 1.1.1
