.travis.yml, ajax/backup.php, lib/app.php, tests/apptest.php, tests/bootstrap.php, tests/phpunit.xml, update.php
Resubmission of https://github.com/owncloud/updater/pull/67
Fixes #66 
Fixes #69
=> Fix for 66

lib/app.php, tests/apptest.php
Porting #81 to master.
Should fix tests with current core master
=>  Use IConfig instead of IAppConfig

css/updater.css
=> Fix update wizard li-floating

css/updater.css
=> [stable8] Fix update wizard li-floating

lib/location/apps.php, lib/updater.php
=> Change include path instead of prepending

css/updater.css
=> [stable7] Fix update wizard li-floating

admin.php, ajax/channel.php, appinfo/routes.php, js/app.js, js/controllers.js, lib/app.php, lib/channel.php, templates/admin.php, tests/apptest.php
Closes https://github.com/owncloud/updater/issues/95
=> Add release channels support

templates/admin.php
=> Add update notice. Closes #111

templates/update.php
Ref https://github.com/owncloud/updater/issues/107
More details:
https://github.com/owncloud/core/pull/14540
=> Prevent 8.1 update for win

templates/admin.php
Prevent updates to OC8 on unsupported environment
=> Check PHP version before update. Closes #107

ajax/channel.php, lib/channel.php
Depends on https://github.com/owncloud/core/pull/16339
=> Override update channel value via DB

lib/app.php
=> New server URL

appinfo/info.xml
Please review @VicDeo @MorrisJobke
=> Remove bogus redundant version number

lib/downloader.php
Closes https://github.com/owncloud/updater/issues/140
=> Use core download facilities

js/controllers.js, lib/helper.php, templates/admin.php
… and make it more comprehensible and nicer in general (see #172). Fix some very short sentences in error messages. Fix DIV not closing.
Disclaimer: I am not sure about the »i« and tooltip for »last checked«, though. – Opinions welcome!
=> Rewrite text on admin-page to reduce it … (#172)

appinfo/application.php, lib/helper.php
Backport of https://github.com/owncloud/updater/pull/179
=> [Stable8.2] Skip version check for daily builds

templates/admin.php
Note that it's about major releases and it can take up to a month.
Fixes #183
=> update text on delay of availability

lib/location/core.php
=> [Stable8.2] Use 8.2

lib/helper.php
Backport of https://github.com/owncloud/updater/pull/179
=> [Stable8.1]  Skip version check for daily builds

box.json
UPD (by VicDeo)
how-to:
get bx.phar from https://github.com/box-project/box2#as-a-phar-recommended and run
./box.phar build
the updater tool can then be executed using
./setup.phar
=> Adding box.json to generate setup.phar

app/config/container.php, src/Command/ExecuteCoreUpgradeScriptsCommand.php, src/Command/InfoCommand.php, src/Command/UpgradeShippedAppsCommand.php, src/Tests/Utils/AppManagerTest.php, src/Tests/Utils/ConfigReaderTest.php, src/Tests/Utils/RegistryTest.php, src/Utils/Locator.php
As per https://github.com/owncloud/core/issues/18721
Steps are taken from https://github.com/owncloud/core/issues/18721#issuecomment-143215159
Moved from https://github.com/owncloud/updater/pull/187
From https://github.com/owncloud/updater/pull/187#issuecomment-164742026
=> Continue for 9.0

src/Command/DetectCommand.php
=> Show Network error details

.travis.yml
Let's see. Would be awesome if that works for the speed…
=> Disable sudo in travis.yml

pub/css/main.css, src/Resources/views/partials/login.php
=> Better looking login page

pub/js/main.js, src/Resources/views/partials/inner.php
Required for the auth changes in core. PR coming there as well soon.
@VicDeo Mind testing whether it still works currently? If yes then please merge and I can finish the core PR :smile:
=> Use server URL

composer.json, composer.lock, src/Controller/IndexController.php, vendor/composer/autoload_files.php, vendor/composer/autoload_psr4.php, vendor/composer/installed.json, vendor/ircmaxell/password-compat/LICENSE.md, vendor/ircmaxell/password-compat/composer.json, vendor/ircmaxell/password-compat/lib/password.php, vendor/ircmaxell/password-compat/version-test.php, vendor/symfony/polyfill-php55/LICENSE, vendor/symfony/polyfill-php55/Php55.php, vendor/symfony/polyfill-php55/Php55ArrayColumn.php, vendor/symfony/polyfill-php55/README.md, vendor/symfony/polyfill-php55/bootstrap.php, vendor/symfony/polyfill-php55/composer.json
Requires https://github.com/owncloud/core/pull/22276
=> Use bcrypt for shared secret

src/Command/ExecuteCoreUpgradeScriptsCommand.php, src/Command/PostUpgradeCleanupCommand.php, src/Command/UpgradeShippedAppsCommand.php, src/Console/Application.php, src/Utils/ConfigReader.php, src/Utils/Locator.php
Ref  https://github.com/owncloud/updater/issues/242
=> Use oc datadir instead of own

application.php, src/Controller/IndexController.php
=> Add some type hinting

appinfo/info.xml
=> Compatible with 8.2 only

src/Utils/BzipExtractor.php, src/Utils/OccRunner.php, src/Utils/ZipExtractor.php
=> Override default symfony process timeoute to infinity

src/Utils/OccRunner.php
Depends on https://github.com/owncloud/core/pull/22218
=> Suppress extra messages while asking for json

pub/css/main.css, pub/js/main.js, src/Resources/views/partials/inner.php
=> WebUI Design update

src/Command/DisableNotShippedAppsCommand.php, src/Command/EnableNotShippedAppsCommand.php
to survive between AJAX requests
=> Store disabled apps in session

src/Command/ExecuteCoreUpgradeScriptsCommand.php
Fixes https://github.com/owncloud/updater/issues/225
=> Do not trigger app upgrade while upgrading core

app/bootstrap.php, application.php
=> [Stable 9] Chdir to updater directory before taking any other action

src/Command/CheckpointCommand.php, src/Resources/views/partials/inner.php, src/Tests/Utils/CheckpointTest.php, src/Utils/Checkpoint.php, src/Utils/FilesystemHelper.php, src/Utils/Locator.php
Fixes https://github.com/owncloud/updater/issues/268
=> Add date to checkpoint list

src/Command/CheckpointCommand.php, src/Resources/views/partials/inner.php, src/Tests/Utils/CheckpointTest.php, src/Utils/Checkpoint.php, src/Utils/FilesystemHelper.php, src/Utils/Locator.php
Backport of https://github.com/owncloud/updater/pull/274
Fixes https://github.com/owncloud/updater/issues/268
=> [Stable9] Add date to checkpoint list 

src/Command/CheckpointCommand.php, src/Utils/Checkpoint.php
Backport of https://github.com/owncloud/updater/pull/276
Fixes #259
=> [stable9] Removing checkpoints (inc. removal after restore)

src/Command/CheckpointCommand.php, src/Utils/Checkpoint.php
=> Removing checkpoints (inc. removal after restore)

src/Command/ExecuteCoreUpgradeScriptsCommand.php
fixes #280
Makes sure, that apps dir is restored.
(didn't use finally block to keep compatibility with PHP <5.5)
=> always restore moved apps dir

src/Command/ExecuteCoreUpgradeScriptsCommand.php
=> [stable9] always restore moved apps dir

src/Controller/IndexController.php
=> [stable9] fixes wrong invalid password ui

src/Controller/DownloadController.php
=> Validate checksum only if path exists

src/Controller/DownloadController.php
=> [Stable9] Validate checksum only if path exists

src/Command/DetectCommand.php
Ref #292 
Before:
Current version is 9.1.0.0
ownCloud daily is found online
After:
Current version is 9.1.0.0
Online version is 100.0.0.0 [daily]
=> Show version and channel instead of version string

src/Command/CheckSystemCommand.php, src/Command/DetectCommand.php, src/Command/ExecuteCoreUpgradeScriptsCommand.php, src/Command/PostUpgradeCleanupCommand.php, src/Utils/FilesystemHelper.php, src/Utils/Locator.php
@DeepDiver1975 requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/owncloud/updater/
=> Scrutinizer Auto-Fixes

src/Utils/AppManager.php
=> Add disabled app to the disabled app list on success

src/Console/Application.php, src/Utils/Checkpoint.php, src/Utils/Fetcher.php, src/Utils/Locator.php
=> Fix ownCloud spelling

src/Utils/Checkpoint.php, src/Utils/Locator.php
=> Replace 3rdparty

src/Utils/Checkpoint.php, src/Utils/Locator.php
Backport of https://github.com/owncloud/updater/pull/319/
=> [Stable9] Replace 3rdparty

src/Command/ExecuteCoreUpgradeScriptsCommand.php, src/Command/UpgradeShippedAppsCommand.php, src/Utils/FilesystemHelper.php, src/Utils/Locator.php
Backport of https://github.com/owncloud/updater/pull/326
Fixes #318
=> [Stable9] Move extractionBaseDir under the data/updater

src/Utils/FilesystemHelper.php
=> Make rmdirr public

src/Utils/FilesystemHelper.php
=> [Stable9] Make rmdirr public

src/Utils/OccRunner.php
Backport of https://github.com/owncloud/updater/pull/339
Fixes https://github.com/owncloud/updater/issues/335
=> [Stable9] Suppress all warning from occ

src/Utils/Fetcher.php
Requires https://github.com/owncloud/core/pull/24500
=> Read updater server URL from config file

src/Utils/Fetcher.php
Backport of https://github.com/owncloud/core/pull/24500
=> [stable9] Read updater server URL from config file

src/Command/CheckSystemCommand.php, src/Command/DetectCommand.php, src/Command/EnableNotShippedAppsCommand.php, src/Command/ExecuteCoreUpgradeScriptsCommand.php, src/Command/PostUpgradeCleanupCommand.php, src/Command/UpgradeShippedAppsCommand.php, src/Utils/AppManager.php, src/Utils/Checkpoint.php, src/Utils/FilesystemHelper.php, src/Utils/Locator.php
A cumulative backport of 
https://github.com/owncloud/updater/pull/305
https://github.com/owncloud/updater/pull/346
https://github.com/owncloud/updater/pull/347
to make testing easier
Fixes #350 
Obsoletes https://github.com/owncloud/updater/pull/351
=> [Stable9] Fix for Upgrade from 9.0.1 to 9.0.2 fails

src/Command/CheckSystemCommand.php
Backport of https://github.com/owncloud/updater/pull/289
=> [Stable9] Typo Fix

src/Command/CheckSystemCommand.php, src/Console/Application.php, src/Tests/Utils/DocLinkTest.php, src/Utils/DocLink.php
=> Central config of doc link generation

src/Command/CheckpointCommand.php
=> Checkpoint id is undefined when checkpoint creation fails

lib/app.php, lib/updater.php
- use new update server URL
- cast SimpleElement  to string (it can be array of strings otherwise)
- copy crt bundle to `config` directory
Fixes #164 #134
=> Stable8 fixups

lib/app.php, lib/updater.php
- cast SimpleElement to string (it can be array of strings otherwise)
- copy crt bundle to config directory
Fixes #164 #134
=> Stable8.1 fixups

lib/channel.php
- cast SimpleElement to string (it can be array of strings otherwise)
fixes #134
=> Stable8.2 fixups

app/bootstrap.php
Ref https://github.com/owncloud/core/pull/25513
=> Require PHP 5.6.0 or above

lib/channel.php
Fixes https://github.com/owncloud/core/issues/26199
=> Use updater.server.url

lib/app.php
https://github.com/owncloud/core/blob/stable8.1/lib/private/updater.php#L132
=> [Stable8.1] Do not pass server URL

lib/app.php
https://github.com/owncloud/core/blob/stable8/lib/private/updater.php#L103
=> [Stable8] Do not pass server URL

src/Console/Application.php, src/Utils/OccRunner.php
Backport of https://github.com/owncloud/updater/pull/388 (fixes #383)
+
Fix for https://github.com/owncloud/updater/issues/378
=> [Stable9] Fallback to localhost and then to CLI, use --key=value notation for CLI

src/Console/Application.php, src/Controller/IndexController.php
Fixes `cURL error 6: Could not resolve host: status` on master
=> Fix endpoint detection

src/Console/Application.php, src/Utils/OccRunner.php
Fixes #397
forwardport of the second commit from https://github.com/owncloud/updater/pull/395 to Stable9.1
=> [Stable9.1] Fallback to localhost and then to CLI

src/Console/Application.php
PHP 5.4 does not allow that
In stable9.1 already
Not needed for master
=> [stable9] Fix incompatible syntax

src/Utils/Locator.php
=> Reflect 9.2-specific changes

src/Console/Application.php, src/Controller/IndexController.php, src/Utils/OccRunner.php
Forwardport of
https://github.com/owncloud/updater/pull/398
and
https://github.com/owncloud/updater/pull/400
=> Master forwardport fallback

src/Console/Application.php, src/Controller/IndexController.php, src/Utils/Locator.php
=> Init config once

src/Command/PostUpgradeCleanupCommand.php
Backport of https://github.com/owncloud/updater/pull/405
=> [Stable9.1] Retrigger integrity check. Fixes #404

src/Command/PostUpgradeCleanupCommand.php
=> [stable9] Retrigger integrity check. Fixes #404

pub/js/main.js, src/Resources/views/partials/inner.php
Show spinners for all steps Fixes #330 
Links top logo in updater to ownCloud, adds autoredirect to ownCloud after the successful update. Closes https://github.com/owncloud/updater/issues/344
=> UI enhancements

src/Command/ExecuteCoreUpgradeScriptsCommand.php, src/Tests/Command/ExecuteCoreUpgradeScriptsCommandTest.php
Load version and canBeUpgradedFrom from downloaded owncloud  package
Check if migration is possible.
Fixes #406
=> Check possibility of upgrade before replacing files. Fixes #406

src/Utils/Locator.php
=> Fix integrity when migrating from 9.1.x

src/Command/ExecuteCoreUpgradeScriptsCommand.php, src/Tests/Command/ExecuteCoreUpgradeScriptsCommandTest.php
Backport of #426 
Fixes #425
Reproduction steps https://github.com/owncloud/updater/pull/426#issue-231695396
=> CanBeUpgradedFrom could have multiple versions. Fixes #425

src/Utils/Locator.php
=> Add CHANGELOG.md to whitelist

src/Utils/Locator.php
Backport of https://github.com/owncloud/updater/pull/437
Description:
Update from 10.0.2->10.0.3beta with the web updater using owncloud/administration#137.
Expected: no integrity check errors
Actual: CHANGELOG.md is marked as missing file
=> [Stable10] Add CHANGELOG.md to whitelist

src/Utils/Locator.php
Backport of https://github.com/owncloud/updater/pull/437
Tested with migration 9.1.6 to 10.0.3rc1
=> [stable9.1] Add CHANGELOG.md to whitelist

src/Command/ExecuteCoreUpgradeScriptsCommand.php, src/Utils/AppManager.php
=> Fix dealing with apps

src/Utils/Locator.php
=> Add ocm-provider to known localtions

src/Utils/Locator.php
Backport of https://github.com/owncloud/updater/pull/497
=> [Stable10] Add ocm-provider to known localtions

src/Utils/ConfigReader.php
Reference issue #482 and PR #485 - this PR commits the changes committed to master into stable10 per @VicDeo's request
=> [stable10] Fix for updater/application.php cli fatal errors #472 #482 owncloud/core#31425

composer.json, composer.lock
=> Remove paragonie/random_compat from dependencies

Makefile
=> remove unnecessary files

Makefile
For removing logic from https://github.com/owncloud/administration-internal/pull/121 - let's improve the makefile here
=> [stable10] remove unnecessary files in makefile

CHANGELOG.md, Makefile
=>  1.0.0 release

.travis.yml
=> Remove old hhvm checks from Travis

.travis.yml, src/Tests/Command/ExecuteCoreUpgradeScriptsCommandTest.php, src/Tests/Controller/DownloadControllerTest.php, src/Tests/Http/RequestTest.php, src/Tests/Utils/AppManagerTest.php, src/Tests/Utils/CheckpointTest.php, src/Tests/Utils/ConfigReaderTest.php, src/Tests/Utils/DocLinkTest.php, src/Tests/Utils/FeedTest.php, src/Tests/Utils/FetcherTest.php, src/Tests/Utils/OccRunnerTest.php, src/Tests/Utils/RegistryTest.php, src/Tests/bootstrap.php
`phpunit` V5 is rather old.
First move to V6 (this PR).
=> Update phpunit to 6.5

.travis.yml, composer.json, composer.lock
Travis CI is already just testing PHP 7.1 7.2 7.3
This PR changes composer to specify minimum PHP 7.1 and that allows phpunit 7.*
This can be done if it is OK that this app will no longer run on PHP  7.0
=> Update to PHP 7.1 and phpunit 7.5

.drone.star, Makefile, sonar-project.properties
- This PR enables sonarCloud for code coverage.
- https://github.com/owncloud/updater/issues/582
=> [Tests-Only]Enables sonarcloud for code coverage

composer.lock
```
$ composer update
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 2 updates, 0 removals
- Upgrading phpunit/phpunit (8.5.15 => 8.5.16)
- Upgrading symfony/debug (v4.4.22 => v4.4.25)
Writing lock file
```
=> [tests-only] Update PHP dev dependencies

.drone.star, .gitignore, src/Tests/phpunit.xml
Related https://github.com/owncloud/QA/issues/678
- Fix code coverage reporting
- Implement early fail and full-ci in drone CI behavior like what is done in core and other repos
**note** this PR was generated by a automated script
=> [Tests-Only][CI] Update .drone.star file for new changes from activity app

.drone.star
Update drone.star file to the standard version from owncloud/activity
Related https://github.com/owncloud/activity/issues/997
https://github.com/owncloud/activity/pull/998
=> [CI] Update drone.star file to the standard version from owncloud/activity

.drone.star
https://drone.owncloud.com/owncloud/updater/309
".drone.star:1799:14: undefined: selUserNeeded"
Somehow the drone starlark in this repo has got out-of-date in a way that causes an error in the merge CI.
This PR updates the starlark code to the latest, from the activity app.
=> [tests-only] Apply latest .drone.star code

.drone.star, .gitignore
- it is better to use directory references from the dir var, rather than using the hard-coded values in every use case.
-  Applied other starlark changes waiting in activity app
- https://github.com/owncloud/QA/issues/734#issue-1173320353
- CI
=> [full-ci][not-ready]Use directory references and add some activity app pending changes

.drone.star
Part of issue https://github.com/owncloud/QA/issues/818
=> [tests-only] [full-ci] Update CI

CHANGELOG.md
=> Merge back Release 1.1.1
